In [5]:
import tensorflow as tf

### tf.scatter_nd()

方便的用于将sparse_tensor转换为dense_tensor. 指定indices, values, 和dense tensor的shape，就可以把sparse tensor转成dense
(https://docs.w3cub.com/tensorflow~python/tf/scatter_nd)[https://docs.w3cub.com/tensorflow~python/tf/scatter_nd]

In [6]:
def tf_scatter_nd():
    indices = tf.constant([[4], [3], [1], [7]])
    updates = tf.constant([9, 10, 11, 12])
    shape = tf.constant([8])
    scatter = tf.scatter_nd(indices, updates, shape)
    with tf.Session() as sess:
        print(sess.run(scatter))

tf_scatter_nd()

[ 0 11  0 10  9  0  0 12]


In [7]:
def tf_fill():
    res = tf.fill([2,3], 9)
    with tf.Session() as sess:
        print(sess.run(res))

tf_fill()

[[9 9 9]
 [9 9 9]]
